/**
 * Parses the canonical docs/reference/providers.md source file (mirrored
 * into src/data/providers-source.md during the build) into a structured
 * catalog used by the /providers page.
 *
 * The upstream file is generated by `go run ./internal/tools/provider-catalog`
 * and always reflects the real directory tree. By parsing it here instead of
 * walking src/content/docs/docs/reference/providers/, we guarantee the
 * website catalog matches the canonical 110-across-19-categories figure
 * even when a category (e.g. memory stores, server adapters) has no
 * polished doc page yet.
 */

import providersMd from "../data/providers-source.md?raw";

export type ProviderRecord = {
  category: string;       // slug-style key for filtering: "llm", "vectorstore", ...
  categoryLabel: string;  // human label as shown in the source: "LLM", "Vector stores", ...
  categoryPath: string;   // source package directory: "llm/providers", "server/adapters", ...
  slug: string;           // provider id: "anthropic", "pgvector"
  name: string;           // same as slug, kept for symmetry with older code
  title: string;          // preferred display title (falls back to slug)
  description: string;    // the godoc first line from the source table
  href: string;           // target URL on the website (reference page if one exists, else null-safe)
};

export type CategoryRecord = {
  slug: string;
  label: string;
  count: number;
};

/** Convert a category label like "Vector stores" / "STT (speech-to-text)" to a filter slug. */
function labelToSlug(label: string, pathHint: string): string {
  // Prefer the source package path where available, because that's what the
  // actual on-disk directories are named ("vectorstore", "voice", "mcp", ...).
  // e.g. `rag/vectorstore/providers` → "vectorstore"
  //      `voice/stt/providers`       → "stt"
  //      `server/adapters`           → "server"
  //      `protocol/mcp/providers`    → "mcp"
  const cleaned = pathHint
    .replace(/\/providers$/, "")
    .replace(/\/adapters$/, "");
  const parts = cleaned.split("/").filter(Boolean);
  // Take the last segment as the primary slug, unless it's a generic word
  // like "providers" or "adapters".
  const last = parts[parts.length - 1] || "";
  return last.toLowerCase();
}

/** Canonical display order. Categories not in this list append to the end. */
const CATEGORY_ORDER = [
  "llm",
  "vectorstore",
  "embedding",
  "loader",
  "memory",
  "stt",
  "tts",
  "s2s",
  "transport",
  "vad",
  "guard",
  "workflow",
  "observability",
  "eval",
  "state",
  "cache",
  "prompt",
  "mcp",
  "server",
];

/**
 * A handful of categories use a source package path that doesn't yet have
 * a matching /docs/reference/providers/{slug}/ page. Map those to their
 * website destination explicitly. Everything else lands at
 * /docs/reference/providers/{slug}/{provider}/.
 *
 * Categories marked as null have NO docs destination — the catalog card
 * renders as a plain description without a link.
 */
const CATEGORY_HREF_BASE: Record<string, string | null> = {
  llm: "/docs/reference/providers/llm",
  vectorstore: "/docs/reference/providers/vectorstore",
  embedding: "/docs/reference/providers/embedding",
  loader: "/docs/reference/providers/loader",
  memory: null, // not in the current docs tree
  stt: "/docs/reference/providers/voice",
  tts: "/docs/reference/providers/voice",
  s2s: "/docs/reference/providers/voice",
  transport: "/docs/reference/providers/transport",
  vad: "/docs/reference/providers/vad",
  guard: "/docs/reference/providers/guard",
  workflow: "/docs/reference/providers/workflow",
  observability: "/docs/reference/providers/observability",
  eval: "/docs/reference/providers/eval",
  state: "/docs/reference/providers/state",
  cache: "/docs/reference/providers/cache",
  prompt: "/docs/reference/providers/prompt",
  mcp: "/docs/reference/providers/mcp",
  server: null, // not in the current docs tree
};

type ParseState = "outside" | "in-section" | "in-table";

function parseProvidersMarkdown(md: string): {
  providers: ProviderRecord[];
  categories: CategoryRecord[];
  totalClaim: number | null;
} {
  const providers: ProviderRecord[] = [];
  const categoryMap = new Map<string, CategoryRecord>();
  let totalClaim: number | null = null;

  let state: ParseState = "outside";
  let currentLabel = "";
  let currentSlug = "";
  let currentPath = "";
  let currentHrefBase: string | null = null;

  const sectionHeading = /^##\s+([^—`]+?)\s*[—–-]\s*`([^`]+)`/;
  const tableRow = /^\|\s*`([^`]+)`\s*\|\s*(.+?)\s*\|\s*$/;
  const totalLine = /\*\*Total providers:\*\*\s*(\d+)/;

  for (const rawLine of md.split("\n")) {
    const line = rawLine.trimEnd();

    const total = line.match(totalLine);
    if (total) {
      totalClaim = Number(total[1]);
    }

    const heading = line.match(sectionHeading);
    if (heading) {
      currentLabel = heading[1].trim();
      currentPath = heading[2].trim();
      currentSlug = labelToSlug(currentLabel, currentPath);
      currentHrefBase = CATEGORY_HREF_BASE[currentSlug] ?? null;
      state = "in-section";
      continue;
    }

    if (state === "outside") continue;

    // The table header row looks like `| Provider | Description |`.
    // We use the backtick-wrapped provider cell pattern to filter those out.
    const row = line.match(tableRow);
    if (row) {
      state = "in-table";
      const slug = row[1].trim();
      const description = row[2].trim().replace(/\s+/g, " ");
      if (!currentSlug) continue;
      const hrefBase = currentHrefBase;
      const href = hrefBase ? `${hrefBase}/${slug}/` : "";
      providers.push({
        category: currentSlug,
        categoryLabel: currentLabel,
        categoryPath: currentPath,
        slug,
        name: slug,
        title: slug,
        description,
        href,
      });

      const existing = categoryMap.get(currentSlug);
      if (existing) {
        existing.count += 1;
      } else {
        categoryMap.set(currentSlug, {
          slug: currentSlug,
          label: currentLabel,
          count: 1,
        });
      }
    }
  }

  const categories = [...categoryMap.values()].sort((a, b) => {
    const ai = CATEGORY_ORDER.indexOf(a.slug);
    const bi = CATEGORY_ORDER.indexOf(b.slug);
    const an = ai === -1 ? 1000 : ai;
    const bn = bi === -1 ? 1000 : bi;
    if (an !== bn) return an - bn;
    return a.label.localeCompare(b.label);
  });

  providers.sort((a, b) => {
    const ai = CATEGORY_ORDER.indexOf(a.category);
    const bi = CATEGORY_ORDER.indexOf(b.category);
    const an = ai === -1 ? 1000 : ai;
    const bn = bi === -1 ? 1000 : bi;
    if (an !== bn) return an - bn;
    return a.slug.localeCompare(b.slug);
  });

  return { providers, categories, totalClaim };
}

const parsed = parseProvidersMarkdown(providersMd);

export const providers: ProviderRecord[] = parsed.providers;
export const categories: CategoryRecord[] = parsed.categories;
export const totalProviders: number = providers.length;
export const totalCategories: number = categories.length;

/** The number the source file claims ("Total providers: 110 across 19 categories").
 * If this disagrees with the row-count, something in providers.md drifted. */
export const totalClaimedByUpstream: number | null = parsed.totalClaim;
